# Generated by Django 4.2.10 on 2024-03-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
