# Generated by Django 4.2.10 on 2024-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_fooditem_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="image_url",
        ),
        migrations.AddField(
            model_name="shop",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
